# Site settings
title: vytas.io
description: "Java EE architecture, design and development tips, hints, code snippets and other random ideas."
url: "http://vytas.io"
twitter_username: vytas.io
github_username:  vytas.io
facebook_username:  vytas.io

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /blog/:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

